using System;

namespace PMBOK
{
	class ProjectCharter {}
	class ProjectStatementOfWork {}
	class BusinessCase {}
	class Agreements {}
	class EnterpriseEnvironmentalFactors {}
	class OrganizationalProcessAssets {}
	class StakeholderRegister {}
	class ProcurementDocuments {}
	class ProjectManagementPlan {}
	class OutputsFromOtherProcesses {}
	class ScopeManagementPlan {}
	class RequirementsManagementPlan {}
	class RequirementsDocumentation {}
	class RequirementsTraceabilityMatrix {}
	class StakeholderManagementPlan {}
	class ProjectScopeStatement {}
	class ProjectDocumentsUpdates {}
	class ScopeBaseline {}
	class ScheduleManagementPlan {}
	class ActivityList {}
	class ActivityAttributes {}
	class MilestoneList {}
	class ProjectScheduleNetworkDiagrams {}
	class ActivityResourceRequirements {}
	class ResourceBreakdownStructure {}
	class ResourceCalendars {}
	class RiskRegister {}
	class ActivityCostEstimates {}
	class ActivityDurationEstimates {}
	class ScheduleBaseline {}
	class ProjectSchedule {}
	class ScheduleData {}
	class ProjectCalendars {}
	class ProjectManagementPlanUpdates {}
	class ProjectStaffAssignments {}
	class CostManagementPlan {}
	class BasisOfEstimates {}
	class HumanResourceManagementPlan {}
	class CostBaseline {}
	class ProjectFundingRequirements {}
	class QualityManagementPlan {}
	class ProcessImprovementPlan {}
	class QualityMetrics {}
	class QualityChecklists {}
	class CommunicationsManagementPlan {}
	class RiskManagementPlan {}
	class ProjectDocuments {}
	class ProcurementManagementPlan {}
	class ProcurementStatementOfWork {}
	class MakeOrBuyDecisions {}
	class ChangeRequests {}
	class FinalProductServiceOrResultTransition {}
	class OrganizationalProcessAssetsUpdates {}
	class AcceptedDeliverables {}
	class ClosedProcurements {}
	class Deliverables {}
	class WorkPerformanceData {}
	class ApprovedChangeRequests {}
	class QualityControlMeasurements {}
	class TeamPerformanceAssessments {}
	class EnterpriseEnvironmentalFactorsUpdates {}
	class IssueLog {}
	class WorkPerformanceReports {}
	class ProjectCommunications {}
	class SelectedSellers {}
	class ResourceCalendar {}
	class SellerProposals {}
	class ChangeLog {}
	class ScheduleForecasts {}
	class CostForecasts {}
	class ValidatedChanges {}
	class WorkPerformanceInformation {}
	class VerifiedDeliverables {}
	class SourceSelectionCriteria {}
}
